// <auto-generated />
namespace SoftwareEngineeringTechnologyCourses.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PopulateCoursesTableSemester4TechElective : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PopulateCoursesTableSemester4TechElective));
        
        string IMigrationMetadata.Id
        {
            get { return "201801011316128_PopulateCoursesTableSemester4TechElective"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
