// <auto-generated />
namespace SoftwareEngineeringTechnologyCourses.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PopulateCoursesTableSemester6TechElective : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PopulateCoursesTableSemester6TechElective));
        
        string IMigrationMetadata.Id
        {
            get { return "201801011341551_PopulateCoursesTableSemester6TechElective"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
